"use client";

import { useState } from "react";
import { RELEASE_PROOF_CONTRACT_ADDRESS, submitReleaseProof, type WalletAddress } from "@/lib/genlayer";

declare global { interface Window { ethereum?: { request: (args: { method: string; params?: unknown[] }) => Promise<unknown> } } }

export default function VerifyPage() {
  const [packageName, setPackageName] = useState("genlayer-js"); const [version, setVersion] = useState("1.1.8"); const [githubReleaseUrl, setGithubReleaseUrl] = useState("https://github.com/yeagerai/genlayer-js/releases"); const [registryUrl, setRegistryUrl] = useState("https://www.npmjs.com/package/genlayer-js/v/1.1.8"); const [changelogUrl, setChangelogUrl] = useState("https://github.com/yeagerai/genlayer-js/blob/main/CHANGELOG.md"); const [address, setAddress] = useState(RELEASE_PROOF_CONTRACT_ADDRESS); const [wallet, setWallet] = useState<WalletAddress | null>(null); const [message, setMessage] = useState("Fill in the three sources, then submit them to GenLayer validators."); const [releaseId, setReleaseId] = useState(""); const [busy, setBusy] = useState(false);
  async function connectWallet() { if (!window.ethereum) throw new Error("No browser wallet detected."); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as WalletAddress[]; if (!accounts[0]) throw new Error("No wallet account returned."); setWallet(accounts[0]); return accounts[0]; }
  async function verify() { try { setBusy(true); setReleaseId(""); setMessage("Requesting wallet and waiting for GenLayer consensus..."); const account = wallet ?? await connectWallet(); const result = await submitReleaseProof({ walletAddress: account, packageName, version, githubReleaseUrl, registryUrl, changelogUrl, contractAddress: address as `0x${string}` }); setReleaseId(result.releaseId); setMessage("Consensus accepted the release. Inspect the exact stored record below."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  return <main className="mx-auto min-h-screen max-w-3xl px-5 py-10 text-[#15171a]"><a className="pill" href="/">ReleaseProof</a><h1 className="mt-7 text-4xl font-semibold">Verify a software release</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-[#52616d]">Submit release evidence to the deployed contract. ReleaseProof does not decide locally: it returns only the ID produced by an accepted GenLayer write.</p><section className="tool-panel mt-8 grid gap-4"><Field id="package" label="Package name" value={packageName} setValue={setPackageName} /><Field id="version" label="Version" value={version} setValue={setVersion} /><Field id="release" label="GitHub release or tags URL" value={githubReleaseUrl} setValue={setGithubReleaseUrl} /><Field id="registry" label="Package registry URL" value={registryUrl} setValue={setRegistryUrl} /><Field id="changelog" label="Changelog or docs URL" value={changelogUrl} setValue={setChangelogUrl} /><Field id="address" label="Studio contract address" value={address} setValue={setAddress} /><div className="flex flex-wrap gap-3"><button className="action-button" onClick={() => connectWallet().then(() => setMessage("Wallet connected.")).catch((error) => setMessage(error.message))}>Connect wallet</button><button className="action-button primary" disabled={busy} onClick={verify}>{busy ? "Awaiting consensus" : "Verify release"}</button></div><p className="text-sm text-[#52616d]">{message}</p></section>{releaseId ? <section className="result-card mt-6"><span className="field-label">Accepted release ID</span><code className="mt-2 block break-all text-lg">{releaseId}</code><a className="mt-4 inline-block text-sm font-semibold text-[#155e75]" href={`/explorer?releaseId=${encodeURIComponent(releaseId)}&address=${encodeURIComponent(address)}`}>Inspect on-chain record</a></section> : null}</main>;
}
function Field({ id, label, value, setValue }: { id: string; label: string; value: string; setValue: (value: string) => void }) { return <label className="grid gap-2" htmlFor={id}><span className="field-label">{label}</span><input className="text-input" id={id} value={value} onChange={(event) => setValue(event.target.value)} /></label>; }
